# Multiple Linear Regression

## Importing the libraries

In [1]:
import numpy as np
import pandas as pd

Creating the dataset

y = b0 +b1*x1 +b2*x2 +b3*x3 +b4*x4


In [9]:
from numpy.random import rand

df  = pd.DataFrame(rand( 50 , 3)*10, columns = 'Hours_studied Hours_slept iQ '.split())
df.head(2) ## this rand fn in this shows that there will be 50 rows and 3 columns which can have values till 10

Hours_studied  Hours_slept        iQ
0       9.192373     8.517490  9.623341
1       8.463959     8.372144  3.376198

In [10]:
from random import choice

location = []
for i in range(50):
    
    location.append(choice(["New Delhi" , "Pune" , "Bangalore"]))
 

df['Location'] = location

df.head()

Hours_studied  Hours_slept        iQ   Location
0       9.192373     8.517490  9.623341       Pune
1       8.463959     8.372144  3.376198  New Delhi
2       9.829397     3.364057  7.675410  New Delhi
3       0.923074     5.672812  2.218119  New Delhi
4       6.773743     2.608290  9.375153  New Delhi

In [14]:
df['Marks'] = (1.73 + (3.34*df['Hours_studied'])
                    + (2.45*df['Hours_slept'])
                    + (1.83*df['iQ']  ))
df['Marks'] =  df['Marks'] +np.random.rand(50)*20
               
df.to_csv('Students.csv',index=False)


In [15]:
df.head()

Hours_studied  Hours_slept        iQ   Location      Marks
0       9.192373     8.517490  9.623341       Pune  71.149024
1       8.463959     8.372144  3.376198  New Delhi  64.043939
2       9.829397     3.364057  7.675410  New Delhi  57.507402
3       0.923074     5.672812  2.218119  New Delhi  23.427172
4       6.773743     2.608290  9.375153  New Delhi  54.977915

## Importing the dataset

In [16]:
dataset = pd.read_csv('Students.csv')

X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values
print(X)

[[9.192373134602716 8.517490297969564 9.623340835800224 'Pune']
 [8.463958886096965 8.372143594118672 3.3761982061779605 'New Delhi']
 [9.829396569764056 3.3640572665064417 7.675410184917728 'New Delhi']
 [0.92307441753944 5.672812108333659 2.2181187081071627 'New Delhi']
 [6.773743188741003 2.608290028209513 9.375152604294335 'New Delhi']
 [3.663500528942396 1.2039312365981758 6.4232658321468215 'New Delhi']
 [8.935647711483533 6.211605329997729 0.255313310005254 'New Delhi']
 [3.447774681128384 4.480733826109105 8.099611579294985 'New Delhi']
 [2.6359083885232093 9.29632351095673 4.8815516003315125 'Bangalore']
 [9.988550194581332 6.565554859195423 2.21922980103244 'New Delhi']
 [2.8768817448171244 8.554153967095905 5.13141902441332 'New Delhi']
 [2.7478476397914484 2.5438119049071477 8.701888717632402 'Pune']
 [7.874997152298965 8.690796125389216 6.089855013378775 'Pune']
 [6.416621274794948 1.0497169517412253 1.3148663938359515 'Pune']
 [7.541000125975956 4.520016715070984 1.544102

In [17]:
print(y)

[71.14902442 64.04393857 57.5074021  23.42717163 54.97791503 47.78071851
 59.79606626 48.24954143 42.73692233 63.55684737 42.91424258 47.52923317
 78.25819758 35.07247413 54.92003432 56.2403796  37.15264704 61.34514486
 48.94632186 60.70826612 44.77001783 63.28662824 52.025174   52.13949897
 47.84031674 33.2968655  60.02264687 73.14772145 24.08673759 47.12007189
 57.20777812 65.93871286 45.78169262 20.89141058 34.86960718 47.14532401
 54.01564423 55.23213514 46.18923582 38.39204712 54.68260318 69.91959493
 76.08906577 37.06775967 66.90397113 50.95168865 39.81915938 35.21421731
 69.31087045 57.13506929]


## Encoding categorical data

In [18]:
from sklearn.compose import ColumnTransformer 
##allows different columns of the input to be transformed separately and the features generated by each transformer will be 
## concatenated to form a single feature space. This is useful for heterogeneous or columnar data,
## to combine several feature extraction mechanisms or transformations into a single transformer.
from sklearn.preprocessing import OneHotEncoder

##The input to transformer should be array-like of integers or strings, denoting the values taken on by categorical (discrete)
## features. This creates binary column for each category and returns a sparse matrix or dense array (depending on the sparse_output parameter)
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [3])],  remainder='passthrough')
print(ct)

X = np.array(ct.fit_transform(X))

ColumnTransformer(remainder='passthrough',
                  transformers=[('encoder', OneHotEncoder(), [3])])


In [20]:
print(X)

[[0.0 0.0 1.0 9.192373134602716 8.517490297969564 9.623340835800224]
 [0.0 1.0 0.0 8.463958886096965 8.372143594118672 3.3761982061779605]
 [0.0 1.0 0.0 9.829396569764056 3.3640572665064417 7.675410184917728]
 [0.0 1.0 0.0 0.92307441753944 5.672812108333659 2.2181187081071627]
 [0.0 1.0 0.0 6.773743188741003 2.608290028209513 9.375152604294335]
 [0.0 1.0 0.0 3.663500528942396 1.2039312365981758 6.4232658321468215]
 [0.0 1.0 0.0 8.935647711483533 6.211605329997729 0.255313310005254]
 [0.0 1.0 0.0 3.447774681128384 4.480733826109105 8.099611579294985]
 [1.0 0.0 0.0 2.6359083885232093 9.29632351095673 4.8815516003315125]
 [0.0 1.0 0.0 9.988550194581332 6.565554859195423 2.21922980103244]
 [0.0 1.0 0.0 2.8768817448171244 8.554153967095905 5.13141902441332]
 [0.0 0.0 1.0 2.7478476397914484 2.5438119049071477 8.701888717632402]
 [0.0 0.0 1.0 7.874997152298965 8.690796125389216 6.089855013378775]
 [0.0 0.0 1.0 6.416621274794948 1.0497169517412253 1.3148663938359515]
 [0.0 1.0 0.0 7.5410001259

## Splitting the dataset into the Training set and Test set

In [21]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train , y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)
y_test

array([24.08673759, 47.52923317, 42.91424258, 69.91959493, 57.5074021 ,
       73.14772145, 46.18923582, 65.93871286, 52.025174  , 54.97791503])

## Training the Multiple Linear Regression model on the Training set

In [22]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

## Predicting the Test set results

In [23]:
y_pred = regressor.predict(X_test)

np.set_printoptions(precision=2)  ##number of digits to be printed after point
print("\n\n\nPredicted  Actual")
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))




Predicted  Actual
[[32.76 24.09]
 [44.26 47.53]
 [48.98 42.91]
 [60.6  69.92]
 [67.8  57.51]
 [61.54 73.15]
 [41.89 46.19]
 [71.84 65.94]
 [55.27 52.03]
 [58.57 54.98]]


In [24]:

np.set_printoptions(precision=2)
print(np.concatenate((X_test ,y_pred.reshape(len(y_pred),1) ,y_test.reshape(len(y_test),1)) ,1))

[[1.0 0.0 0.0 3.04302545277504 2.045824318659508 2.82955914950099
  32.75851593239052 24.086737592329925]
 [0.0 0.0 1.0 2.7478476397914484 2.5438119049071477 8.701888717632402
  44.26080822433545 47.5292331702216]
 [0.0 1.0 0.0 2.8768817448171244 8.554153967095905 5.13141902441332
  48.97555552058192 42.91424258004911]
 [0.0 0.0 1.0 4.095990623090372 9.64337131151585 7.729906058917572
  60.60482177636412 69.9195949324981]
 [0.0 1.0 0.0 9.829396569764056 3.3640572665064417 7.675410184917728
  67.79871069011418 57.50740210039718]
 [1.0 0.0 0.0 7.987045857847603 9.893972976210922 0.955276239738192
  61.54059585718094 73.14772144631563]
 [0.0 1.0 0.0 0.2049907256608563 8.830628087358335 6.162357068797847
  41.892750326047334 46.18923582082909]
 [0.0 0.0 1.0 8.903356153362783 8.794169371397254 5.365719351258972
  71.83891667221181 65.93871285801522]
 [0.0 0.0 1.0 5.447026470243332 5.431228102739531 6.425625246079619
  55.26662522085785 52.02517399564089]
 [0.0 1.0 0.0 6.773743188741003 2.60

In [25]:
len(y_pred)

10

In [26]:
y_test

array([24.09, 47.53, 42.91, 69.92, 57.51, 73.15, 46.19, 65.94, 52.03,
       54.98])

In [27]:
y_pred

array([32.76, 44.26, 48.98, 60.6 , 67.8 , 61.54, 41.89, 71.84, 55.27,
       58.57])

In [ ]:
help(np.random.rand)*10